### PR TITLE
Add ability to update article tags

### PR DESCRIPTION
**Pull request by zelark**
Although it's out of the [spec](https://github.com/gothinkster/realworld/tree/master/api#update-article), I believe it makes sense to add. Especially that the [official demo](https://demo.realworld.io) allows you to update article tags.

### CODE REVIEW

**Comment by zelark** [comment]
Btw, I added a little description above. @furkan3ayraktar, what do you think? If some additional changes required, I will do it.

**Comment by zelark** [comment]
Hi! How's it doing?

**Comment by zelark** [comment]
Found out that there was a problem with previous solution, it didn't take into account a case when user want to delete all the tags from an article. So I added one more test, and fixed the problem.

**Comment by furkan3ayraktar** [comment]
Hi @zelark, thanks for taking time to add this! 

I also feel that it makes sense to add update article functionality (and many others), however I don't want to go beyond the RealWorld specs. I'll keep this PR here, so if people visiting repo needs it, they can use your code.

**Pull request closed without merging**
